### ISSUE TITLE
Prototip: Rastgele Bulmaca

### ISSUE THREAD

**Issue by omersuatdemir** [omersuatdemir/Satranc101DiscordBot#23]
Kısaca: belirlediğimiz puan aralığında rastgele bulmacalar bulacak bir prototip.

**Comment by metincetin** [comment]
lichess'in 3m puzzle içeren bir database'i varmış https://database.lichess.org/#puzzles
bu kullanılabilir. 

**kullanıcı hamleleri nasıl girmeli?**

Kullanıcıdan istediği kadar hamle girmesini bekleyebiliriz. 4 hamlelik bir bulmacada, eğer iki hamle girerse (/puzzle move,move şeklinde), tüm hamleler doğru olduğu durumda o pozisyonun görselini sadece o kullanıcı görecek şekilde atabiliriz. Eğer girilen hamlelerden sırayla biri yanlışsa, yanlış olan hamleyi "e4 yanlış" diye belirtiriz. Eğer isterse (/puzzle move) şeklinde tek tek çözebilir, her hamlede pozisyonun görselini alır, isterse de (/puzzle move,move,move,move) şeklinde tüm hamleleri girip sonuca ulaşır.

**Comment by omersuatdemir** [comment]
> lichess'in 3m puzzle içeren bir database'i varmış https://database.lichess.org/#puzzles bu kullanılabilir.
> 
> **kullanıcı hamleleri nasıl girmeli?**
> 
> Kullanıcıdan istediği kadar hamle girmesini bekleyebiliriz. 4 hamlelik bir bulmacada, eğer iki hamle girerse (/puzzle move,move şeklinde), tüm hamleler doğru olduğu durumda o pozisyonun görselini sadece o kullanıcı görecek şekilde atabiliriz. Eğer girilen hamlelerden sırayla biri yanlışsa, yanlış olan hamleyi "e4 yanlış" diye belirtiriz. Eğer isterse (/puzzle move) şeklinde tek tek çözebilir, her hamlede pozisyonun görselini alır, isterse de (/puzzle move,move,move,move) şeklinde tüm hamleleri girip sonuca ulaşır.

Aslında ilk defa yapmıyoruz böyle bir şeyi daha önceden yapılmış botlar var. Kullandıkları yöntem de gayet makul. Sıfırdan düşünmemize gerek yok. Bir bulmaca atılacak daha sonra kullanıcılardan tek hamlelik cevaplar beklenilecek. Tüm cevapları aynı anda yazmalarına gerek yok. Hem hamle hamle tahtayı güncellemiş oluruz. Yarışma formatında olacağından dediğin gibi cevaplar doğru da olsa yanlış da olsa sonraki hamleler sadece komudu kullanan kullanıcıya görünmeli. Birisi bulmacayı tamamen doğru bitirdikten sonra sohbete bir mesaj atarız. Şu kullanıcı bulmacayı çözdü fln diye. Orada spoiler işaretli olarak cevabı da koyarız. Ama diğerleri yine görmemeli hala devam edebilmeliler çözmeye.

**Comment by omersuatdemir** [comment]
done
