### ISSUE TITLE
Duyuruya Lichess Hesapları da Eklensin

### ISSUE THREAD

**Issue by omersuatdemir** [omersuatdemir/Satranc101DiscordBot#76]
Daha sonradan arama yapılmasının kolaylaştırılması için, duyuru yapılırken birinci ikinci üçüncü kısımlarına sadece discord hesapları değil lichess hesapları da eklensin.

**Comment by omersuatdemir** [comment]
done

**Comment by glitchychoppa** [comment]
💯🫵💯👌👌👑😊😊💕😂😒😒❤️❤️❤️😒😒😘
